### ISSUE TITLE
Change CONFIG_REFERENCE.md to be a manpage

### ISSUE THREAD

**Issue by emersion** [emersion/maddy#47]
scdoc is probably the way to go.

**Comment by foxcpp** [comment]
Manpages are cool and I would like to revamp configuration as a whole while migrating to them (split internal details from moments important for users, provide a good introduction for new users, etc).

Can we have HTML-rendered manpages somewhere so it will be convenient to view them in browsers?
Especially I would like to see the ability to link to certain sections in conversations and in README.md since maddy.conf(5) is going to be big and will be growing with time (another way is to split it into separate manpages on per-module basis).

**Comment by emersion** [comment]
>Can we have HTML-rendered manpages somewhere so it will be convenient to view them in browsers?

We could, there are a few man-to-HTML converters.
